namespace EdhDeckBuilder.Core.Cards;

/// <summary>
/// A card proposed by an <see cref="EdhDeckBuilder.Core.Abstractions.ISuggestionSource"/> as a
/// candidate for inclusion in a deck.
/// </summary>
/// <remarks>
/// <para>
/// Candidates carry the raw signals from the data source — how commonly the card appears and
/// which thematic section it came from — but no deck-context reasoning. The distinction is
/// intentional: Infrastructure can observe patterns across thousands of decks, but it cannot
/// reason about <em>this</em> specific deck (what roles are already covered, what the commander's
/// strategy is, what other cards have been chosen).
/// </para>
/// <para>
/// That reasoning step belongs to the Agent layer, which elevates a subset of candidates to
/// <c>CardSuggestion</c>s: cards chosen for the final 99, each accompanied by a human-readable
/// reason generated by the LLM with full deck context (e.g. "Fills your Ramp gap",
/// "Redundant with Sol Ring and Mind Stone already in the deck").
/// The Agent also surfaces a short runner-up list — candidates that were evaluated but not
/// chosen — so the user can review near-misses and make manual overrides.
/// See <c>CardSuggestion</c> and <c>DeckBuildResult</c> in the Agent layer (TODO).
/// </para>
/// <para>
/// <c>Synergy</c> is intentionally absent from this type. It is an EDHREC-internal metric
/// that a second suggestion source could not faithfully reproduce, so it does not belong
/// in a Core contract. The Agent may use synergy as an internal signal when ranking candidates,
/// but that is an Agent-layer concern.
/// </para>
/// </remarks>
public sealed record CardCandidate(
    Card Card,

    /// <summary>
    /// Fraction of comparable decks that include this card (0–1), as reported by the source.
    /// Higher means more universally adopted; use as one ranking signal, not a verdict
    /// (a card popular in 80% of decks may still be wrong for a specific strategy or commander).
    /// </summary>
    double Inclusion,

    /// <summary>
    /// Thematic grouping assigned by the source, e.g. "High Synergy Cards", "Spellslinger Cards",
    /// "Top Cards", "Ramp". Tells the Agent <em>why</em> the source considers this card relevant,
    /// which is a stronger archetype-fit signal than inclusion alone.
    /// </summary>
    string Section);
