<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\EdhDeckBuilder.Core\EdhDeckBuilder.Core.csproj" />
    <ProjectReference Include="..\EdhDeckBuilder.Infrastructure\EdhDeckBuilder.Infrastructure.csproj" />
    <ProjectReference Include="..\EdhDeckBuilder.Agent\EdhDeckBuilder.Agent.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
